name: PR Check

on:
  pull_request: ~

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - shell: python
        run: |
          obj = """${{ toJSON(github) }}"""
          print(obj)

      - name: Checkout
        uses: actions/checkout@v4
        with:
           fetch-depth: 2
      
      - name: Check .github dir
        run: |
          echo "==> PR Head is a fork: ${{ github.event.pull_request.head.repo.fork }}"
          echo "==> Changed files:"
          git diff --name-only HEAD^1 HEAD
          echo "==> Violating files"
          git diff --name-only HEAD^1 HEAD | grep '^\.github/' || echo "--None--"
          count=$(git diff --name-only HEAD^1 HEAD | grep -c '^\.github/') || count=0
          
          if [[ "${{ github.event.pull_request.head.repo.fork }}" = "true" && $count -gt 0 ]]; then
              echo "==> Found $count violations!"
              echo "::error::Changed workflow in PR from fork!"
              exit 1
          fi
          echo "All OK"


